#!/bin/bash

usage() {
cat << EOF
===================================================================
getScriptLocation
===================================================================
Purpose: Gets the location of the script being run
Arguments: \$1 -> SLURM job ID
Optional arguments: -v -> verbose -d -> get script directory
Author: Sam Fletcher
Contact: s.o.fletcher@exeter.ac.uk
===================================================================
EOF
    exit 0
}

while getopts vd OPT; do
    case "$OPT" in
        v ) verbose=TRUE ;;
        d ) directory=TRUE ;;
        \? ) usage ;;
    esac
done

shift $((OPTIND-1))

jobID=$1

if [[ -z "${jobID}" ]]; then usage; fi

if [[ "${verbose}" == "TRUE" ]]; then
    echo -n "Job ${jobID} is located at: "
fi

location=$(\
scontrol show job "${jobID}" | \
grep "Command" | \
awk '{print $1}' | \
awk 'BEGIN {FS="="} {print $2}' \
)

if [[ "${directory}" == "TRUE" ]]; then
    location=$(dirname "${location}")
fi

echo "${location}"
